# Dependencies
markdown:         rdiscount
pygments:         true

# Permalinks
permalink:        pretty

# Server
destination:      ./_site
exclude:          [".editorconfig", ".gitignore", ".bowerrc", "jshintrc", "bower.json", "config.json", "Gruntfile.js", "package.json", "manifest.cfg", "rules.xml", "docs", "node_modules", "bower_components", "README.md", "dist", "assets", "less", "js", "overrides"]
port:             9001

# Custom vars
current_version:  3.0.0
repo:             https://github.com/vwc/buildout.re.git
